# Generated by Django 5.1.1 on 2024-09-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_slug',
            field=models.SlugField(auto_created=True, blank=True, editable=False, unique=True),
        ),
    ]
