# Generated by Django 5.1 on 2024-08-26 08:55

import django.core.validators
import world_of_speed.profilee.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3), world_of_speed.profilee.validators.validate_username_length, world_of_speed.profilee.validators.validate_username_symbols])),
                ('email', models.CharField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(21, message='Age requirement: 21 years and above.')])),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
