# Generated by Django 5.1.1 on 2024-09-24 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='First name should contain only letters.', regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='First name should contain only letters.', regex='^[a-zA-Z]+$')])),
                ('profile_picture', models.URLField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('DO NOT SHOW', 'DO NOT SHOW')], default='DO NOT SHOW')),
            ],
        ),
    ]
