# Generated by Django 5.1.2 on 2024-10-25 08:21

import django.core.validators
import world_of_speed_app_2.user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(15), world_of_speed_app_2.user_profile.validators.username_validator])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(help_text='Age requirement: 21 years and above.', validators=[django.core.validators.MinValueValidator(21)])),
                ('password', models.CharField(validators=[django.core.validators.MaxLengthValidator(20)])),
                ('first_name', models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('last_name', models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
