# Generated by Django 5.0.4 on 2024-09-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('second_name', models.CharField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
