# Generated by Django 5.0.4 on 2024-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_personinfor_stats_alter_personinfor_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfor',
            name='stats',
            field=models.CharField(blank=True, default=1, null=True),
        ),
    ]
