# Generated by Django 5.0.4 on 2024-09-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_studentwithchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personinfor',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personinfor',
            name='stats',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentwithchoices',
            name='f_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentwithchoices',
            name='status',
            field=models.CharField(choices=[(1, 'DRAFT'), (2, 'PUBLISHED'), (3, 'ARCHIVED')], max_length=20),
        ),
    ]
