# Generated by Django 5.0.4 on 2024-09-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_personinfor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwithchoices',
            name='status',
            field=models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUBLISHED'), (3, 'ARCHIVED')], max_length=20),
        ),
    ]
