# Generated by Django 5.0.4 on 2024-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_delete_studentwithchoices_remove_personinfor_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='topic',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'Java Script'), ('C#', 'C Sharp'), ('OTHER', 'Other')], default='Other'),
        ),
    ]
