# Generated by Django 5.0.4 on 2024-10-06 06:30

import forumApp.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_posts_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[forumApp.posts.validators.BadLanguageValidator]),
        ),
    ]
