# Generated by Django 5.0.4 on 2024-10-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_posts_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonInfor',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
