# Generated by Django 5.1 on 2024-08-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_users_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='photo',
            new_name='photo_1',
        ),
        migrations.AddField(
            model_name='users',
            name='photo_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
