# Generated by Django 5.1.2 on 2024-10-25 08:35

import django.core.validators
import django.db.models.deletion
import world_of_speed_app_2.car.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Rally', 'Rally'), ('Open-Wheel', 'Open-Wheel'), ('Kart', 'Kart'), ('Drag', 'Drag'), ('Other', 'Other')], validators=[django.core.validators.MaxLengthValidator(10)])),
                ('model', models.CharField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15)])),
                ('year', models.IntegerField(validators=[world_of_speed_app_2.car.validators.car_year_validator])),
                ('image_url', models.URLField(default='https://...', error_messages={'unique': 'This image URL is already in use! Provide a new one.'}, unique=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user_profile.profile')),
            ],
        ),
    ]
